### ISSUE TITLE
Make configuration compatible with Neo4j V3

### ISSUE THREAD

**Issue by carlosforero** [cohesivestack/ineo#24]
- V3 compatible http port config
- V3 compatible https port config
- V3 compatible ineo status check

**Comment by cayasso** [comment]
@carlosforero Is there a quick workaround to support neo4j v3 that I can apply?
Thanks!

**Comment by carlosforero** [comment]
Hi @cayasso.

@tlauwyck and @barttv, have been working on this. I think this week v1.1 will be ready.

If you like you can join to our Gitter group.

Thank you for your support.

**Comment by OmarKan** [comment]
Any word on this ?

**Comment by carlosforero** [comment]
Ineo 1.1.0 has been released. This has support to last Neo4j version, including bolt port.

To update Ineo: ineo update

In case Ineo is not installed, then: curl -sSL http://getineo.cohesivestack.com | bash -s install

To get help about how to create an instance setting bolt port: ineo help create
