### ISSUE TITLE
new action(s) to get and set a config parameter

### ISSUE THREAD

**Issue by ogmueller** [cohesivestack/ineo#38]
I would like to add new config action(s) to get or set a certain setting from one or all instances.

Something like:

```
# ineo get-config <instances...> <parameter>
# ineo set-config <instances...> <parameter> <value>
```

In general this is not to complicated to do for a single instance, but I struggle with a couple of things and would like to discuss them first:

1. One, some or all instances
If we want to get or set a parameter in the config, it would be nice to have the choice to do so with one, some or all instances. But there is some trouble here.
1.1. Problem with multiple instances
Using multiple instances as CLI arguments is not working in other actions (e.g. start) even though from the documentation point of view, it says "[instance_names ...]  Name of one or more instances to start (optional)". But as far as I tried, it is only possible to either not add an instance (so all get started) or enter a single one. Multiple don't work.
1.2. CLI argument handling
If we want to allow this kind of things in set-config, CLI argument handling is not so easy, e.g. if the value is empty.
1.3 How to define "all"
Can we always assume that no instance means all? Would it make sense to change instances from being a CLI argument to an option? maybe a "-n <name>" or "-i <instance>" option. That could make argument/option handling easier in the future and could deliver a more consistent UI.
2. Output of get-config
how should we do the output? If someone likes to use this command in scripts, I could imagine that the pure value of the config parameter is most preferable (1):
```
# ineo get-config twitter dbms.windows_service_name
neo4j
```
On the other side the following output is more human readable and would also allow a "search pattern" (2):
```
# ineo get-config twitter "dbms.memory.*"
dbms.memory.heap.initial_size=512m
dbms.memory.heap.max_size=512m
dbms.memory.pagecache.size=10g
```
And if we want to allow output of multiple/all instances, we need to add the instance name somehow? (3):
```
# ineo get-config "dbms.memory.*"

  > instance 'twitter'
    dbms.memory.heap.initial_size=512m
    dbms.memory.heap.max_size=512m
    dbms.memory.pagecache.size=10g

  > instance 'google'
    dbms.memory.heap.initial_size=384m
    dbms.memory.heap.max_size=384m
    dbms.memory.pagecache.size=5g
```
3. Remove/disable with set-config
How should we put an empty value or how can we comment out a value? Maybe with a option like "-c" (comment) or "-d" (disable/delete)?
4. Config check
Does anyone know, if we can test the configuration somehow? Like apache does with "apachectl configtest".

**Comment by carlosforero** [comment]
The commits related with this feature were branched in https://github.com/cohesivestack/ineo/tree/feature/set-configuration

So, Ineo version 1.1.0 was released without them.

I comment later about this feature.

**Comment by ogmueller** [comment]
Hey Carlos, any suggestions on instance selection? and output format? It is really hard to say, which one is best or preferred. 

With the instances I tend to got with
  - one or all, which means we need to remove/correct this in the rest of the actions
  - change to options, which makes things more flexible and allow us to use "some instances" in an easy way. We could even introduce an asterix pattern. When using options the only questions left is, what is "all". The absent of an option or a special option (-a) or a special name ("all" or "*")?

**Comment by carlosforero** [comment]
Hi @ogmueller 

Next Saturday, I will review all your comments and PR. Also I would like to know if you like to collaborate as manager in this project, since currently I'm not working any project with Neo4j and my other projects is not allowing me enough time for that.

**Comment by ogmueller** [comment]
Hey, looking forward to you comments :-)

Of course I would like to move this project forward and help as a co-manager. We have a lot of projects with neo4j currently and ineo really helps us. I just hope that you can still support me a bit especially because this is your project. You are the initiator and obviously you know why certain things are like they are :-)

**Comment by carlosforero** [comment]
Here my thoughts about `get-config` and `set-config`

1) `set-config` should be used only with individual instances. Try to set to all instances is too much, and could be very confusing for the user when there are multiple versions and the entry name could be not valid for some version.

So, `set-config` should be:
```
set-config [options] <instance_name...> <parameter> <value>

OPTIONS:
    -d    Disable (comment out) the parameter.
            If this option is used then the value is not required
    -q    Write setting without confirmation

```

2) `get-config` should work with multiple instances. I think the option `-a` should be used for all instances. The Ineo commands which assume that all instances are used, are commands where the instance name is the last option. But for this case the last option is the config parameter name.

Using wildcards would be great. For this case, if an entry doesn't exists in the config file for some Neo4j instance, then the output won't display it. .

```
# ineo get-config -a "dbms.memory.*"

  > instance 'twitter'
    dbms.memory.heap.initial_size=512m
    dbms.memory.heap.max_size=512m
    dbms.memory.pagecache.size=10g
    dbms.memory.new_feature=20g

  > instance 'google'
    dbms.memory.heap.initial_size=384m
    dbms.memory.heap.max_size=384m
    dbms.memory.pagecache.size=5g
```

```
# ineo get-config -a "dbms.memory.new_*"

  > instance 'twitter'
    dbms.memory.new_feature=20g

  > instance 'google'

```

3) When an explicit instance is used, the output should show the parameter name, in this way the output will be very explicit about the entry used when wildcard is used:

```
# ineo get-config twitter dbms.windows_service*
dbms.windows_service_name=neo4j
```

4) If wildcard is not used, then an error could be displayed if the entry doesn't exists

```
# ineo get-config twitter dbms.windows_service_nameE
WARNING: "dbms.windows_service_nameE" doesn't exist in the "twitter" configuration
```

```
# ineo get-config -a "dbms.memory.new_feature"

  > instance 'twitter'
    dbms.memory.new_feature=20g

  > instance 'google'
      WARNING: "dbms.memory.new_feature" doesn't exist in the "google" configuration
```

Maybe it's not bad idea to add an option `-q` to hide the warning message.

```
# ineo get-config -q twitter dbms.windows_service_nameE
```
