### ISSUE TITLE
BOLT port for instances after the second

### ISSUE THREAD

**Issue by marco-brandizi** [cohesivestack/ineo#40]
I'm using ineo installed a few days ago. I don't get on which port the BOLT protocol is accessible for the instances created after the second. The create command doesn't allow me to set it up, the status command doesn't list BOLT ports, I cannot find it on config files or logs.

I need it for clients using the Java driver.

Thanks in advance.

**Comment by carlosforero** [comment]
Version with BOLT port support will be released on next days. I'll notify you.

**Comment by marco-brandizi** [comment]
Thank you, @carlosforero. For the moment, I've found a workaround: create a new instance with -v 3.3.1 (default is 2.x and that's why I wasn't seeing BOLT stuff in the instance's config files), then edit <instance>/conf/neo4j.conf and change the BOLT port there.

**Comment by carlosforero** [comment]
Ineo 1.1.0 has been released.

To update Ineo: `ineo update`

In case Ineo is not installed, then: `curl -sSL http://getineo.cohesivestack.com | bash -s install`

To get help about how to create an instance setting bolt port: `ineo help create`

I'm going to close this issue. If you have any issue with new version, please let me know.
