### ISSUE TITLE
permission/ACL problem creating new instance

### ISSUE THREAD

**Issue by ogmueller** [cohesivestack/ineo#41]
if someone is using ACL or certain permissions on the INEO_HOME folder or its subfolders, those permissions will not work or get into effect, because ineo is creating the instance in a different folder (/tmp) and then moves it to the INEO_HOME folder:
`mv ${TEMP_DIR}/${version}/neo4j-${edition}-${version} ${INEO_HOME}/instances/${instance_name}`

some examples:
```
chmod g+s $INEO_HOME/instances
```
or
```
setfacl -Rdm g:somegroup:rwx $INEO_HOME/instances
setfacl -Rm g:somegroup:rwx $INEO_HOME/instances
```

if an instance gets created now, the instance itself won't have any of these permissions/ACLs.

An alternative would be to create a "hidden" (".") instance, which is not seen by "ineo instances", and once it has been successfully created, rename it to the given instance_name:
```
tar -xzf ${INEO_HOME}/neo4j/${tar_name} \
    -C ${INEO_HOME}/instances/.${instance_name}
mv ${INEO_HOME}/instances/.${instance_name} ${INEO_HOME}/instances/${instance_name}
```

I could implement and test it, if this is a good solution?

**Comment by carlosforero** [comment]
I think the "hidden" "." folder is ok. Currently Ineo uses the `trap` command to delete the temporal folder if the installation is aborted, which prevents garbage files.

**Comment by ogmueller** [comment]
Added the temp folder to the trap as well, so now it gets removed anyhow.
