### ISSUE TITLE
autostart option / service / systemd

### ISSUE THREAD

**Issue by ogmueller** [cohesivestack/ineo#44]
If ineo is installed by root, it would be really nice to also install a service (e.g. systemd) to allow instances to get started automatically.

Maybe a system that LXC is using. There each instance can define, if it wants to get started by the service. LXC uses these [optional parameter](https://linuxcontainers.org/lxc/manpages/man5/lxc.container.conf.5.html#lbBJ) to decide if and how to start a container:
```
# auto start container
lxc.start.auto = 1
lxc.start.delay = 10
lxc.start.order = 20
lxc.group = prod
```
 
When introducing this, i would actually change the way ineo stores metadata information for an instance (`.version` and `.edition`) because those are getting more and more. Maybe we can combine all metadata information in a file `.ineo` within an instance? A big question is, which format to use? ini format or just bash "readable" format?

ini format (needs parser):
```
[general]
version=1.2.3
edition=community

[start]
auto=1
delay=2
...
```

bash variables (can be included):
```
neo4j.version=1.2.3
neo4j.community=community
ineo.start.auto=1
ineo.start.delay=2
...
```

The service in general would be really nice, because all necessary instances would be available after reboot and the service could also define, when to start and what it needs to do so (e.g. filesystem, firewall, network, ...)

**Comment by carlosforero** [comment]
@ogmueller 

This would be a nice feature, but perhaps we should make it optional with some switch like `-S`, otherwise, I think, Ineo could be intrusive and that could be annoying for some users, even using root.
