### ISSUE TITLE
How to Load dump file 

### ISSUE THREAD

**Issue by priteshks007** [cohesivestack/ineo#50]
How to Load dump file, When I try to load then says that Neo4j is running stop and try again
![screenshot 7](https://user-images.githubusercontent.com/31968643/47357066-65e18980-d6e3-11e8-99e1-b652844c21dc.png)

**Comment by priteshks007** [comment]
I stopped the Neo4j instance but not working

**Comment by ogmueller** [comment]
If you need support for Neo4j you should visit their [support website](https://support.neo4j.com/hc/en-us) and post your question on the forum.
